<?php

return [
    'co.uk' => 'uk',
    'org.uk' => 'uk',
    'net.uk' => 'uk',
    'me.uk' => 'uk',
    'ltd.uk' => 'uk',
    'plc.uk' => 'uk',
    'sch.uk' => 'uk',
    'ac.uk' => 'uk',
    'gov.uk' => 'uk',
    'mod.uk' => 'uk',
    'mil.uk' => 'uk',
    'nhs.uk' => 'uk',
    'police.uk' => 'uk',

    'mex.com' => 'centralnic',
    'radio.am' => 'centralnic',
    'eu.com' => 'centralnic',
    'radio.fm' => 'centralnic',
    'cn.com' => 'centralnic',
    'ru.com' => 'centralnic',
    'uk.net' => 'centralnic',
    'br.com' => 'centralnic',
    'hu.net' => 'centralnic',
    'us.com' => 'centralnic',
    'za.com' => 'centralnic',
    'in.net' => 'centralnic',
    'co.nl' => 'centralnic',
    'gb.net' => 'centralnic',
    'se.net' => 'centralnic',
    'com.se' => 'centralnic',
    'com.de' => 'centralnic',
    'jpn.com' => 'centralnic',
    'co.com' => 'centralnic',
    'us.org' => 'centralnic',
    'jp.net' => 'centralnic',
    'uk.com' => 'centralnic',
    'de.com' => 'centralnic',
    'ae.org' => 'centralnic',
    'co.no' => 'centralnic',
    'gr.com' => 'centralnic',
    'sa.com' => 'centralnic',
    'it.com' => 'centralnic',
];
